AWSTemplateFormatVersion: 2010-09-09

Parameters:
  StackFamily:
    Type: String
    Default: ecs-blue-green-demo
  Username:
    Type: String
  AccessToken:
    Type: String
    NoEcho: true

Resources:
  SecretsManagerSecretDocker:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${StackFamily}-secrets-docker"
      Description: docker personal access token
      SecretString: !Sub |
        {
          "username": "${Username}",
          "access-token": "${AccessToken}"
        }
